cmake_minimum_required(VERSION 3.10)
project(inno_clientsdk)

add_subdirectory(src)
add_subdirectory(test)

# option(MAKE_SHARED "Build a shared library" OFF)

# if(NOT MAKE_SHARED)
# if(EXISTS "${CMAKE_SOURCE_DIR}/apps/example")
# add_subdirectory(apps/example)
# endif()

# if(EXISTS "${CMAKE_SOURCE_DIR}/apps/tools/get_pcd/")
# add_subdirectory(apps/tools/get_pcd)
# endif()
# endif()
